version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: sistema-local-maps
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1818
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
